name: .NET Core CI/CD

on:
  push:
    branches:
      - master  # Trigger workflow on push to the main branch
  pull_request:
    branches:
      - master  # Trigger workflow on PRs targeting main
  workflow_dispatch:  # Manual trigger option

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore Dependencies
      run: dotnet restore WebApp/WebApp.csproj

    - name: Build
      run: dotnet build WebApp/WebApp.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test WebApp/WebApp.csproj --no-build --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.base_ref == 'main')

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Debug Info
      run: |
        echo "Ref: $GITHUB_REF"
        echo "Event: $GITHUB_EVENT_NAME"
        echo "PR Base Ref: ${{ github.base_ref }}"

    - name: Publish
      run: dotnet publish WebApp/WebApp.csproj -c Release -o ./publish

    - name: Deploy to Server (Example for Azure)
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'WebApp-Dotnet-RG-Devansh-POC'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./publish
