name: .NET Core CI

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'  # Specify the version you are using

    - name: Restore Dependencies
      run: dotnet restore WebApp/WebApp.csproj

    - name: Build
      run: dotnet build WebApp/WebApp.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test WebApp/WebApp.csproj --no-build --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'  # Deploy only on the main branch

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Publish
      run: dotnet publish WebApp/WebApp.csproj -c Release -o ./publish

    - name: Deploy to Server (Example for Azure)
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'WebApp-Dotnet-RG-Devansh-POC'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./publish
